# Generated by Django 4.0.6 on 2022-07-28 14:55

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default='temp/dummy_image.png', max_length=255, null=True, upload_to=account.models.get_profile_image_filepath),
        ),
    ]
